language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get install -y openmpi
  - pip install --upgrade pip
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install --upgrade pytest
install: pip install .
script:
  - cd florin 
  - pytest
