language: python
matrix:
  include:
      - name: "Python 3.5-3.6 on Trusty"
        python:
          - "3.5"
          - "3.6"
        dist: "trusty"
      - name: "Python 3.7+ on Xenial"
        python:
          - "3.7"
        dist: "xenial"
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - sudo apt-get install -y libcr-dev mpich
  - pip install --upgrade pip
  - pip install --upgrade pytest
install:
  - pip install .
script:
  - python -m pytest tests
